# Generated by Django 4.2.5 on 2023-09-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_chicken_is_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
