# Generated by Django 4.2.5 on 2023-09-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_chicken_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chicken',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
