# Generated by Django 4.2.5 on 2023-09-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='link',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
