# Generated by Django 4.2.5 on 2023-09-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_department_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
