# Generated by Django 4.2.5 on 2023-09-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_buildings'),
        ('item', '0007_building'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
    ]
