# Generated by Django 4.2.5 on 2023-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('costbuy', models.FloatField(default=0)),
                ('costsell', models.FloatField(default=0)),
            ],
        ),
    ]
