# Generated by Django 4.2.5 on 2023-09-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_items',
            new_name='Shopping_item',
        ),
    ]
