# Generated by Django 4.2.5 on 2023-09-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_shopping_item_shoppingitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoppingitem',
            new_name='Shopping_item',
        ),
    ]
