# Generated by Django 4.2.5 on 2023-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_shoppingitem_shopping_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_item',
            name='offset',
            field=models.FloatField(default=0.1),
        ),
    ]
