# Generated by Django 4.2.5 on 2023-09-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_alter_building_cost_alter_building_cost_in_egg_and_more'),
        ('user', '0002_alter_userprofile_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='buildings_level',
            field=models.ManyToManyField(related_name='buildings_level', to='buildings.building'),
        ),
    ]
