# Generated by Django 4.2.5 on 2023-09-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_alter_building_cost_alter_building_cost_in_egg_and_more'),
        ('user', '0003_userprofile_buildings_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='buildings',
            field=models.ManyToManyField(related_name='user_profiles', to='buildings.building'),
        ),
        migrations.CreateModel(
            name='BuildingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='buildings_level',
            field=models.ManyToManyField(related_name='user_profile_levels', through='user.BuildingLevel', to='buildings.building'),
        ),
    ]
