# Generated by Django 4.2.5 on 2023-09-25 13:57
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_buildings_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('building', models.ForeignKey(on_delete=models.CASCADE, to='buildings.Building')),
                ('user_profile', models.ForeignKey(on_delete=models.CASCADE, to='user.UserProfile')),
            ],
        ),
    ]