# Generated by Django 4.2.5 on 2023-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_buildinglevel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='egg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='egg_per_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='money_per_second',
            field=models.IntegerField(default=0),
        ),
    ]
