# Generated by Django 4.2.5 on 2023-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_buildinglevel_egg_in_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinglevel',
            name='hay_in_storage',
            field=models.IntegerField(default=0),
        ),
    ]
