# Generated by Django 4.2.5 on 2023-09-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_buildinglevel_hay_in_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildinglevel',
            name='hay_in_storage',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hay',
            field=models.IntegerField(default=0),
        ),
    ]
