# Generated by Django 4.2.5 on 2023-09-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_buildinglevel_hay_in_storage_userprofile_hay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='egg',
            new_name='Egg',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='hay',
            new_name='Hay',
        ),
    ]
