# Generated by Django 4.2.5 on 2023-09-27 16:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_egg_userprofile_egg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='int_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=20),
        ),
    ]
