# Generated by Django 4.2.5 on 2023-09-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('owned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Building',
            },
        ),
    ]
