# Generated by Django 4.2.5 on 2023-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
        migrations.RemoveField(
            model_name='building',
            name='link',
        ),
        migrations.AlterField(
            model_name='building',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
