# Generated by Django 4.2.5 on 2023-09-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_building_options_remove_building_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='link',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
