# Generated by Django 4.2.5 on 2023-09-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_building_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='link',
        ),
        migrations.AddField(
            model_name='building',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='income_per_click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='income_per_click_per_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='income_per_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='income_per_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='income_per_second_per_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
