# Generated by Django 4.2.5 on 2023-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_remove_building_link_building_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='cost_in_egg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='cost_per_level',
            field=models.IntegerField(default=0),
        ),
    ]
