# Generated by Django 4.2.5 on 2023-09-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_building_cost_in_egg_building_cost_per_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='cost_in_egg',
        ),
        migrations.AddField(
            model_name='building',
            name='egg_money',
            field=models.BooleanField(default=False),
        ),
    ]
