# Generated by Django 4.2.5 on 2023-09-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_remove_building_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='income_per_click_per_level',
        ),
        migrations.RemoveField(
            model_name='building',
            name='income_per_second_per_level',
        ),
    ]
