# Generated by Django 4.2.5 on 2023-09-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_remove_building_cost_per_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='egg_money',
            new_name='cost_in_egg_bool',
        ),
        migrations.AddField(
            model_name='building',
            name='cost_in_egg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='income_per_click_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='income_per_click_in_egg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='income_per_second_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='income_per_second_in_egg',
            field=models.IntegerField(default=0),
        ),
    ]
