# Generated by Django 4.2.5 on 2023-09-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_rename_egg_money_building_cost_in_egg_bool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='income_per_click_bool',
            new_name='income_per_click_in_egg_bool',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='income_per_second_bool',
            new_name='income_per_second_in_egg_bool',
        ),
    ]
