# Generated by Django 4.2.5 on 2023-09-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_rename_income_per_click_bool_building_income_per_click_in_egg_bool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='cost_in_egg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='income_per_click',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='income_per_click_in_egg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='income_per_second',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='income_per_second_in_egg',
            field=models.FloatField(default=0),
        ),
    ]
