# Generated by Django 4.2.5 on 2023-09-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_alter_building_cost_alter_building_cost_in_egg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
