# Generated by Django 4.2.5 on 2023-09-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_alter_building_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='cost_in_egg',
            new_name='eggs_in_seconds',
        ),
        migrations.RemoveField(
            model_name='building',
            name='cost_in_egg_bool',
        ),
        migrations.RemoveField(
            model_name='building',
            name='income_per_click',
        ),
        migrations.RemoveField(
            model_name='building',
            name='income_per_click_in_egg',
        ),
        migrations.RemoveField(
            model_name='building',
            name='income_per_click_in_egg_bool',
        ),
        migrations.RemoveField(
            model_name='building',
            name='income_per_second',
        ),
        migrations.RemoveField(
            model_name='building',
            name='income_per_second_in_egg',
        ),
        migrations.RemoveField(
            model_name='building',
            name='income_per_second_in_egg_bool',
        ),
    ]
