# Generated by Django 4.2.5 on 2023-09-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_rename_cost_in_egg_building_eggs_in_seconds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='eggs_in_seconds',
            new_name='eggs_per_seconds',
        ),
    ]
