# Generated by Django 4.2.5 on 2023-09-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_rename_eggs_in_seconds_building_eggs_per_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='eggs_per_seconds',
            new_name='eggs_per_second',
        ),
    ]
