# Generated by Django 4.2.5 on 2023-09-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0017_rename_eggs_per_seconds_building_eggs_per_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='egg_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='egg_in_storage',
            field=models.FloatField(default=0),
        ),
    ]
