# Generated by Django 4.2.5 on 2023-09-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0018_building_egg_capacity_building_egg_in_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='egg_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
