# Generated by Django 4.2.5 on 2023-09-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0020_alter_building_egg_in_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='eggs_per_second',
            new_name='eggs_per_click',
        ),
    ]
