# Generated by Django 4.2.5 on 2023-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_rename_eggs_per_second_building_eggs_per_click'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='egg_in_storage',
        ),
    ]
